# Generated by Django 4.0.5 on 2022-06-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rating_content_average_rating_design_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
