# Generated by Django 4.0.5 on 2022-06-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='technologies',
        ),
    ]
